name: book_app_rafi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.20.0
  firebase_auth: 4.12.0
  cloud_firestore: 4.12.2
  firebase_storage: 11.4.1
  nb_utils: 6.0.6
  intl: 0.18.1
  convex_bottom_bar: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
  assets: 
    - assets/icon/login_icon.png
  uses-material-design: true

