// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_dF2Tn3h_6tKFBMhCtM81sqVGhfTFME',
    appId: '1:468085733540:web:55f6ab33ac97b3758a0e31',
    messagingSenderId: '468085733540',
    projectId: 'book-app-rafi',
    authDomain: 'book-app-rafi.firebaseapp.com',
    storageBucket: 'book-app-rafi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLNlggp5xRcg3-h0lfAnOOXfSVwf3sawM',
    appId: '1:468085733540:android:e263712383ef4a8c8a0e31',
    messagingSenderId: '468085733540',
    projectId: 'book-app-rafi',
    storageBucket: 'book-app-rafi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvoJNOaet4A0G6YeD3Qn2SFkZ6eslHCg',
    appId: '1:468085733540:ios:ab44376e4aae9cc58a0e31',
    messagingSenderId: '468085733540',
    projectId: 'book-app-rafi',
    storageBucket: 'book-app-rafi.appspot.com',
    iosBundleId: 'com.example.bookAppRafi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvoJNOaet4A0G6YeD3Qn2SFkZ6eslHCg',
    appId: '1:468085733540:ios:e16ffa438d122d9b8a0e31',
    messagingSenderId: '468085733540',
    projectId: 'book-app-rafi',
    storageBucket: 'book-app-rafi.appspot.com',
    iosBundleId: 'com.example.bookAppRafi.RunnerTests',
  );
}
